# Generated by Django 5.0.1 on 2024-01-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_bookingdate_booking_bookingdate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItem',
        ),
    ]
